@baseURL = http://localhost:3000
@jwtToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTgsImVtYWlsIjoiam9hbzEyQGVtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MDcyMTY1OSwiZXhwIjoxNzUwNzI1MjU5fQ.JumL9VIDXvRR8mBOvWjIms5KPKfZWN6mmh25TGHhuRc"


### Cadastro de novo usuário
POST {{baseURL}}/public/users
Content-Type: application/json

{
    "name": "João",
    "email": "joao12@email.com",
    "password": "123456",
    "phone": "99548095",
    "role": "admin"
}

### Login de usuário
POST {{baseURL}}/public/login
Content-Type: application/json

{
    "email": "joao12@email.com",
    "password": "123456"
}

### Pegar todos os pets disponível
GET {{baseURL}}/public/pets/available

### Pegar todos os usuários
GET {{baseURL}}/protected/users
Authorization: Bearer {{jwtToken}}

### Pegar usuário por ID
GET {{baseURL}}/protected/users/1
Authorization: Bearer {{jwtToken}}

### Atualizar usuário
PUT {{baseURL}}/protected/users/1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "name": "João",
    "email": "joao@email.com",
    "password": "123456",
    "phone": "99548095"
}

### Deletar usuário por ID
DELETE {{baseURL}}/protected/users/17


### Buscar pet por ID
GET {{baseURL}}/protected/pets/1
Authorization: Bearer {{jwtToken}}

### Cadastrar novo pet
POST {{baseURL}}/protected/pets
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "name": "Luna",
    "age": 2,
    "species": "dog",
    "size": "medium",
    "status": "",
    "description": "Friendly and playful golden retriever"
}

### Atualizar pet
PUT {{baseURL}}/protected/pets/1
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "name": "Luna",
    "age": 3,
    "species": "dog",
    "size": "medium",
    "status": "adopted",
    "description": "Recently adopted golden retriever"
}

### Deletar pet por ID
DELETE {{baseURL}}/protected/pets/1
Authorization: Bearer {{jwtToken}}